### PR TITLE
Update pelicanconf.py

### PR DESCRIPTION
**Pull request by ghost**
Added social links per issue #14.  I included a Github link in addition to Meetup and Twitter.  Please advise any issues.

### CODE REVIEW

**Comment by tylerdave** [comment]
Deploy preview for *clepy-org* ready!

Built with commit 3d097340ea745c843d5dd02b6faa38a0235c35a9

https://deploy-preview-22--clepy-org.netlify.com

**Comment by tylerdave** [comment]
It looks like you made the change in the theme's test config rather than the website's config. Revert that and apply the change to the pelicanconf.py in the root of the repo. Thanks!

**Comment by tylerdave** [comment]
@kvtw Want to fix this PR so we can get it merged? Let me know if you need help!

**Comment by ghost** [comment]
I will asap

**Comment by ghost** [comment]
I'm having trouble with my computer; if urgent feel free to fix. I apologize.

**Comment by tylerdave** [comment]
@kvtw No worries and no need to rush! I just wanted to see if you needed help with this one. If you don't have time right now, that's fine. If you want help I can work with you or we can talk about it at an upcoming meetup.

**Pull request closed without merging**
